# Generated by Django 2.1.7 on 2019-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_auto_20190220_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='horario',
            field=models.TimeField(),
        ),
    ]
