# Generated by Django 2.1.7 on 2019-02-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190216_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagempost',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
        migrations.DeleteModel(
            name='ImagemPost',
        ),
    ]
